name: Deploy VueJS Project

on:
  workflow_dispatch:  # Cho phép bạn chạy thủ công từ UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:         # <-- Đặt đúng cấp job
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build -- --base=/5mins-deploy-vue/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./dist
